---
title: "p8105_hw5_sy3352"
author: "Su Yan"
date: "2025-11-05"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
set.seed(1)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 1

```{r}
same_bday = function(n) {
  generated_bday = sample(1:365, n, replace = TRUE)
  tibble(duplicate_bday = any(duplicated(generated_bday)))
}

sim_results_df = 
  expand_grid(
    sample_size = 2:50,
    iter = 1:10000
  ) |> 
  mutate(
    estimate_df = map(sample_size, same_bday)
  ) |> 
  unnest(estimate_df)

same_bday_prob = sim_results_df |> 
  group_by(sample_size) |> 
  summarize(same_bday_probability = mean(duplicate_bday))

same_bday_prob_pt = same_bday_prob |> 
  ggplot(aes(x = sample_size,
             y = same_bday_probability)) + 
  geom_line()
same_bday_prob_pt
```

## Problem 2
```{r}
each_sample_test = function(mean_repeat) {
  x = rnorm(30, mean = mean_repeat, sd = 5)
  t.test(x, mu = 0, alternative = c("two.sided"), conf.level = 0.95) |> 
    broom::tidy()
}

sim_normal_datasets = 
  expand_grid(
    mean_repeat = 0:6,
    iter = 1:5000
  ) |> 
  mutate(
    sim_normal_df = map(mean_repeat, each_sample_test)) |> 
  unnest(sim_normal_df)

normal_results = sim_normal_datasets |> 
  select(mean_repeat, estimate, p.value) |> 
  mutate(power = if_else(p.value < 0.05, "Reject", "Fail")) 

power_prob = normal_results |> 
  select(-p.value) |> 
  group_by(mean_repeat) |> 
  summarize(estimate_mean = mean(estimate),
            power_proportion = mean(power == "Reject"))

effect_size_power_pt = power_prob |> 
  ggplot(aes(x = mean_repeat,
             y = power_proportion)) + 
  geom_point() + 
  scale_x_continuous(breaks = 0:6) +
  labs(x = "True value of μ", y = "Power of the test")
effect_size_power_pt

estimate_true_mean_pt = power_prob |> 
  ggplot(aes(x = mean_repeat,
             y = estimate_mean)) + 
  geom_point() + 
  scale_x_continuous(breaks = 0:6) +
  scale_y_continuous(breaks = 0:6) +
  labs(x = "True value of μ", y = "Estimated value of μ")
estimate_true_mean_pt

estimate_mean_reject_pt = normal_results |> 
  select(-p.value) |> 
  filter(power == "Reject") |> 
  group_by(mean_repeat) |> 
  summarize(estimate_mean = mean(estimate)) |> 
  ggplot(aes(x = mean_repeat,
             y = estimate_mean)) + 
  geom_point() + 
  scale_x_continuous(breaks = 0:6) +
  scale_y_continuous(breaks = 0:6) +
  labs(x = "True value of μ", y = "Estimated value of μ (when null is rejected)")
estimate_mean_reject_pt
```

## Problem 3
```{r}
homicides_df = read_csv("data/homicide-data.csv") |> 
  mutate(location = sprintf("%s, %s", city, state),
         unsolved = if_else(disposition == "Closed by arrest", 0, 1)) |> 
  select(location, unsolved) 

homicides_summary = homicides_df |> 
  group_by(location) |> 
  summarize(total_homicides = n(),
            unsolved_homicides = sum(unsolved))
homicides_summary
```

```{r}
baltimore_test = homicides_df |> 
  filter(location == "Baltimore, MD") 
baltimore_result = broom::tidy(
    prop.test(x = sum(baltimore_test$unsolved), n = nrow(baltimore_test), 
              conf.level = 0.95, correct = TRUE))
baltimore_result |> pull(estimate) 
baltimore_result |> pull(conf.low) 
baltimore_result |> pull(conf.high) 
```

```{r}
all_city_test = homicides_summary |> 
  mutate(unsolved_proportion = unsolved_homicides/total_homicides) |> 
  mutate(test_summary = purrr::map2(unsolved_homicides, total_homicides, ~prop.test(x = .x, n = .y, conf.level = 0.95, correct = TRUE)),
         test_tidy = map(test_summary, broom::tidy)
         ) |> 
  unnest(test_tidy)

all_city_test_tidy = all_city_test |> 
  select(location, unsolved_proportion, estimate, conf.low, conf.high)

all_city_test_pt = all_city_test_tidy |> 
  ggplot(aes(x = reorder(location, unsolved_proportion), y = estimate)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  labs(x = "City", y = "Estimated proportion of unsolved homicides (95% CI)")
all_city_test_pt
```

